### ISSUE TITLE
Some issue with heroku deployment

### ISSUE THREAD

**Issue by itssubhodiproy** [yashikajotwani12/Menstruated#3]
**_I really like the idea but this project has some issue with heroku deployment. Maybe something with .env variables._**
<hr/>

![image](https://user-images.githubusercontent.com/75121304/195978013-14a74983-acbb-423c-ba77-6c5aa2b9dea3.png)

**Comment by yashikajotwani12** [comment]
Hello @subh-23, Thanks for pointing out, actually that was my Heroku account issue, I have redeployed it and it has started working, do check it out: http://menstruated.herokuapp.com/
